### ISSUE TITLE
Cannot resolve com.p6e.netty:websocket-client:0.0.1

### ISSUE THREAD

**Issue by duzouw** [lidashuang1996/p6e_broadcast#1]

**Comment by duzouw** [comment]
import com.p6e.netty.websocket.client.instructions.P6eInstructionsAbstractAsync;
import com.p6e.netty.websocket.client.product.P6eProduct;
我看了你的0.0.1版本和1.0.0版本都没有这两个类，是不是重复了？

**Comment by lidashuang1996** [comment]
我这个地方采用是自己用 netty 编写的 websocket 客户端 ！ 由于我昨天更新了 netty 编写的 websocket 客户端（优化了 垃圾回收机制 携带 cookies 以及请求头等）。导致这边还没兼容 ！&nbsp;
我稍后跟你发个源码给你 ！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上9:20
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
import com.p6e.netty.websocket.client.instructions.P6eInstructionsAbstractAsync;
 import com.p6e.netty.websocket.client.product.P6eProduct;
 我看了你的0.0.1版本和1.0.0版本都没有这两个类，是不是重复了？

**Comment by lidashuang1996** [comment]
我那个版本有问题，让你产生误解我！ 我很抱歉 ！ 我现在删除掉，放上最新的版本！ 抱歉 。

**Comment by duzouw** [comment]
是的，我看你的git提交记录找到了历史版本。

**Comment by lidashuang1996** [comment]
<dependency&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <groupId&gt;com.p6e.netty</groupId&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <artifactId&gt;p6e-netty-websocket-client</artifactId&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <version&gt;1.0.2</version&gt;
&nbsp; &nbsp; &nbsp; &nbsp; </dependency&gt;

https://github.com/lidashuang1996/p6e_netty_websocket_client&nbsp;下载那个 jar 包！ mevan 包管理账号还没有申请好。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上9:40
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "芝麻故事官方平台-李大双"<1294935733@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
是的，我看你的git提交记录找到了历史版本。

**Comment by duzouw** [comment]
没事没事，还没有感谢大神写的这个项目呢😊，我在github找了十几个斗鱼弹幕的项目好像就你的靠谱点，所以特意来提问。

**Comment by lidashuang1996** [comment]
我现在也在使用这个项目，收集一些斗鱼直播间里面的弹幕和礼物数据。&nbsp;
你喜欢的话给个星星吧 ！&nbsp;


经过这次后，后面基本上不会这样大更了。

我现在在编写关于这方面的，斗鱼文档【礼物数据 等】！
你在使用过程中知道了相关数据含义，可以协助我来完善这个项目！

现在还支持 blibli 火猫 直播平台 。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上9:43
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "芝麻故事官方平台-李大双"<1294935733@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
没事没事，还没有感谢大神写的这个项目呢😊，我在github找了十几个斗鱼弹幕的项目好像就你的靠谱点，所以特意来提问。

**Comment by duzouw** [comment]
哈哈，我还是个萌新，突然想做一下收集直播弹幕数据这方面的项目，准备拿这个数据来做练手，用于搭建我自己的Spring Cloud项目。

**Comment by duzouw** [comment]
这个项目pom.xml好像还需要导入netty依赖包，不然会报Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/channel/异常

**Comment by lidashuang1996** [comment]
那就导入一个吧, 等我mevan账号注册好了就不会这样了 ~&nbsp;
<!-- https://netty.io/downloads.html --&gt;
&nbsp; &nbsp; &nbsp; &nbsp; <dependency&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <groupId&gt;io.netty</groupId&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <artifactId&gt;netty-all</artifactId&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <version&gt;4.1.48.Final</version&gt;
&nbsp; &nbsp; &nbsp; &nbsp; </dependency&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上10:08
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "芝麻故事官方平台-李大双"<1294935733@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
这个项目pom.xml好像还需要导入netty依赖包，不然会报Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/channel/异常

**Comment by duzouw** [comment]
嗯，我已经启动测试成功了！谢谢啦🙏 困扰了我一下午呢😂

**Comment by lidashuang1996** [comment]
你可以关注我的博客 ， 里面可能有一些你以后可能遇到的坑的详解 ！
现在不是很完善，因为我基本没有关注者。导致我动力不是很足 ~~&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上10:12
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "芝麻故事官方平台-李大双"<1294935733@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
嗯，我已经启动测试成功了！谢谢啦🙏 困扰了我一下午呢😂

**Comment by lidashuang1996** [comment]
地址是 http://lidashuang.com



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上10:12
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "芝麻故事官方平台-李大双"<1294935733@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
嗯，我已经启动测试成功了！谢谢啦🙏 困扰了我一下午呢😂

**Comment by duzouw** [comment]
已收藏！不知道你有没有去知乎、csdn、掘金这些论坛去发帖做推广，我觉得你的项目真的蛮好的！
值得更多人关注！我最近也准备弄一下自己的个人博客，网站备案早就做好了，就是一直没时间去弄，但我还是觉得，把自己遇到的问题和收获的技术，写成博客分享给大家，是一件非常有意义的事情，所以请不要放弃一起加油吧！

**Comment by lidashuang1996** [comment]
你可以加我QQ以后做技术交流， 1294935733 .&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duzouw"<notifications@github.com&gt;; 
发送时间: 2020年5月11日(星期一) 晚上10:38
收件人: "lidashuang1996/p6e_broadcast"<p6e_broadcast@noreply.github.com&gt;; 
抄送: "芝麻故事官方平台-李大双"<1294935733@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lidashuang1996/p6e_broadcast] Cannot resolve com.p6e.netty:websocket-client:0.0.1 (#1)





 
已收藏！不知道你有没有去知乎、csdn、掘金这些论坛去发帖做推广，我觉得你的项目真的蛮好的！
 值得更多人关注！我最近也准备弄一下自己的个人博客，网站备案早就做好了，就是一直没时间去弄，但我还是觉得，把自己遇到的问题和收获的技术，写成博客分享给大家，是一件非常有意义的事情，所以请不要放弃一起加油吧！
